### ISSUE TITLE
Add Single Swaps

### ISSUE THREAD

**Issue by gerrrg** [balancer-labs/balpy#2]
A relatively easy addition would be pure single swaps (currently it can only do a one-swap BatchSwap; I actually already have code for this that should be trivial to integrate, it's just not in balpy itself  yet [https://github.com/gerrrg/balancer-tutorials/blob/master/python/swaps/single_swap.py ])

**Comment by avinkhan1** [comment]
Hi yes, its working for me. So I tried to run the singleswap script on balancer tutorials and got an allowance error.
https://kovan.etherscan.io/tx/0x134a03e94e88154c933d5e4499c520de917628acb40562c0a1c4aa5b28bfa16d

Think it missing code for token allowance?

**Comment by gerrrg** [comment]
yeah, the code there assumes that allowances have already been set. If you were to add in the code that's actually executing the single swap to balpy, you should be able to write a test script much like one for batchswaps, which lives in the samples

**Comment by gerrrg** [comment]
if you want to do a quick test on your own though, you could pretty easily just send a token approval through the kovan UI

**Comment by gerrrg** [comment]
done with [this](https://github.com/balancer-labs/balpy/commit/b23ac4672a8d504ec5466ea54a53e6c678b38863) commit
