### ISSUE TITLE
add pool verification for stablePhantom, aaveLinear 

### ISSUE THREAD

**Issue by gerrrg** [balancer-labs/balpy#26]

**Comment by groninge01** [comment]
Hi, I'm guessing we also need something for the PoolType StablePhantomPool [here](https://github.com/balancer-labs/balpy/blob/64f7e78b72569feb12f64b9d5936d0181b307f42/balpy/balpy.py#L1422).

**Comment by gerrrg** [comment]
yup, need to add StablePhantom and AaveLinear pools in there

**Comment by groninge01** [comment]
I actually added the StablePhantomPool [here](https://github.com/groninge01/balpy/tree/update-stable-phantom-pool) but I need to reformat if you want a PR.
Also the balancer-v2-monorepo didn't have the 'fantom' network yet so I update that one [here](https://github.com/groninge01/balancer-v2-monorepo/tree/beethovenx-verify-phantom) too.

After these changes the verify request gets submitted but it still fails :(

`yarn hardhat verify-contract --id 20211208-stable-phantom-pool --name StablePhantomPool --address 0x1352FD97A1828093Bf375F62E088bC196fACd1ee --network fantom --key <ftmscan_apikey> --args 000000000000000000000000000000000000000000000000000000000000002000000000000000000000000020dd72ed959b6147912c2e529f0a0c651c33c9ce000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000001f4000000000000000000000000000000000000000000000000000221b262dd800000000000000000000000000000000000000000000000000000000000000d35090000000000000000000000000000000000000000000000000000000000278d00000000000000000000000000cd983793adb846dce4830c22f30c7ef0c864a7760000000000000000000000000000000000000000000000000000000000000016546865204f6e652054727565204d6574726f6e6f6d6500000000000000000000000000000000000000000000000000000000000000000000000000000000000d4250542d4d6574726f6e6f6d650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000005ddb92a5340fd0ead3987d3661afcd6104c3b757000000000000000000000000b85a3fc39993b2e7e6874b8700b436c212a0051600000000000000000000000000000000000000000000000000000000000000020000000000000000000000005ddb92a5340fd0ead3987d3661afcd6104c3b757000000000000000000000000b85a3fc39993b2e7e6874b8700b436c212a00516000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001 --verbose`

**Comment by gerrrg** [comment]
@groninge01 are you able to verify _any_ pool on fantom using this method, or is it just the StablePhantomPool that's failing?

**Comment by gerrrg** [comment]
but yeah if you could make a PR w/ the StablePhantomPool (that doesn't reformat the entire balpy.py file😉) that would be super appreciated!

**Comment by groninge01** [comment]
> @groninge01 are you able to verify _any_ pool on fantom using this method, or is it just the StablePhantomPool that's failing?

I will try to find another unverified pool (that's not a StablePhantomPool) to verify.

> but yeah if you could make a PR w/ the StablePhantomPool (that doesn't reformat the entire balpy.py file😉) that would be super appreciated!

I copy&pasted my changes directly into github w/o any formatting. See PR #28.

**Comment by groninge01** [comment]
@gerrrg Verifying a StablePool also fails. Please note I'm just a simple frontend dev trying to learn web3 and rn I'm all out of clues of why it is failing. Do you have any hints for me?

**Comment by gerrrg** [comment]
For what it's worth, the Beets guys told me that they haven't been able to use the ether(/ftm)scan API to verify their pools, and that they've had to do everything manually

**Comment by groninge01** [comment]
That's what I have found out too. I have logged a support ticket with ftmscan so I guess I'll have to wait 'n hopefully hear from them then.

**Comment by groninge01** [comment]
:) That repo is were it all started actually. I'll let you one if and when the ftmscan issue gets solved.

**Comment by gerrrg** [comment]
@groninge01 let's move further discussion to #29 

stablePhantom and aaveLinear added with [66a177a](https://github.com/balancer-labs/balpy/commit/66a177aa0ef2e7859311f1eb1e44352a7a6c91c0)
