### ISSUE TITLE
Getting price of swap before doing a swap.

### ISSUE THREAD

**Issue by jornx** [balancer-labs/balpy#27]
Sorry, just getting started to connect Balancer to my Python trading program.
Could you direct me how to see the price of a swap before I do it? 
I have a hard time finding docs on that.

**Comment by gerrrg** [comment]
you're looking for queryBatchSwap -- here's a sample: https://github.com/balancer-labs/balpy/blob/main/samples/batchSwaps/queryBatchSwapSample.py
